eqfeed_callback({
    "type":"FeatureCollection",
    "features":[
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Centro"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.377945,-3.662394]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Vila Militar"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.3835189,-3.6693908]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Jardim Brasilia"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.385903,-3.652947]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Sabak"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.395189,-3.664657]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Caneção"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.386470,-3.665500]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Jardim Tropical"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.388188,-3.656049]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Aeroporto"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.370498,-3.648215]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Vila Conceição"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-45.361194,-3.659374]
            }  
        }
    ]
});